INSERT INTO FACING (NAME) VALUES
  ('NORTH'),
  ('EAST'),
  ('SOUTH'),
  ('WEST');

INSERT INTO MOVEMENT_DIRECTION (NAME) VALUES
  ('FORWARD'),
  ('BACKWARD'),
  ('LEFT'),
  ('RIGHT'),
  ('CASTLE');

INSERT INTO COLOR (NAME, RED, GREEN, BLUE) VALUES
  ('BLACK', 0, 0, 0),
  ('RED', 255, 0, 0),
  ('GREEN', 0, 255, 0),
  ('BLUE', 0, 0, 255),
  ('YELLOW', 255, 255, 0),
  ('PURPLE', 255, 0, 255),
  ('CYAN', 0, 255, 255),
  ('GRAY', 128, 128, 128),
  ('LIGHT GRAY', 211, 211, 211),
  ('WHITE', 255, 255, 255),
  ('PINK', 255, 192, 203),
  ('BROWN', 150, 75, 0),
  ('ORANGE', 255, 127, 0);

INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES
  ('JOSHUA', 'BOYD');

INSERT INTO GAME (AUTHOR_ID, NAME) VALUES
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), 'CLASSIC CHESS');

INSERT INTO BOARD (AUTHOR_ID, NAME, X_DIMENSION, Y_DIMENSION) VALUES
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), 'CLASSIC BOARD', 8, 8);

INSERT INTO GAME_BOARD (GAME_ID, BOARD_ID) VALUES
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), (SELECT BOARD_ID FROM BOARD WHERE NAME = 'CLASSIC BOARD'));

INSERT INTO PIECE (AUTHOR_ID, NAME) VALUES
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), 'PAWN'),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), 'KNIGHT'),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), 'BISHOP'),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), 'ROOK'),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), 'QUEEN'),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), 'KING');

INSERT INTO GAME_PIECE (GAME_ID, PIECE_ID) VALUES
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'),(SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'),(SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'),(SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'),(SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'),(SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'),(SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'));

INSERT INTO GAME_SETUP (GAME_ID, X, Y, PIECE_ID, COLOR_ID, FACING_ID) VALUES
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 1, 1, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 2, 1, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 3, 1, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 4, 1, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 5, 1, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 6, 1, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 7, 1, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 8, 1, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 1, 2, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 2, 2, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 3, 2, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 4, 2, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 5, 2, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 6, 2, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 7, 2, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 8, 2, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'WHITE'), (SELECT FACING_ID FROM FACING WHERE NAME = 'NORTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 1, 7, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 2, 7, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 3, 7, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 4, 7, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 5, 7, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 6, 7, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 7, 7, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 8, 7, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 1, 8, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 2, 8, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 3, 8, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 4, 8, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 5, 8, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 6, 8, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 7, 8, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), 8, 8, (SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT COLOR_ID FROM COLOR WHERE NAME = 'BLACK'), (SELECT FACING_ID FROM FACING WHERE NAME = 'SOUTH'));

INSERT INTO MOVEMENT_TYPE (NAME) VALUES
  ('SLIDE'),
  ('JUMP');

INSERT INTO MOVEMENT (AUTHOR_ID, MOVEMENT_TYPE_ID, NAME, STEP_MIN, STEP_MAX) VALUES
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'PAWN SINGLE STEP', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'PAWN INITIAL JUMP', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'PAWN CAPTURE LEFT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'PAWN CAPTURE RIGHT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'PAWN CAPTURE ENPASSANT LEFT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'PAWN CAPTURE ENPASSANT RIGHT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'ROOK FORWARD', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'ROOK LEFT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'ROOK RIGHT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'ROOK BACKWARD', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'JUMP'), 'KNIGHT FORWARD LEFT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'JUMP'), 'KNIGHT FORWARD RIGHT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'JUMP'), 'KNIGHT LEFT FORWARD', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'JUMP'), 'KNIGHT LEFT BACKWARD', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'JUMP'), 'KNIGHT RIGHT FORWARD', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'JUMP'), 'KNIGHT RIGHT BACKWARD', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'JUMP'), 'KNIGHT BACKWARD LEFT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'JUMP'), 'KNIGHT BACKWARD RIGHT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'BISHOP FORWARD LEFT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'BISHOP FORWARD RIGHT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'BISHOP BACKWARD LEFT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'BISHOP BACKWARD RIGHT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'QUEEN FORWARD', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'QUEEN FORWARD LEFT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'QUEEN FORWARD RIGHT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'QUEEN LEFT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'QUEEN RIGHT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'QUEEN BACKWARD', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'QUEEN BACKWARD LEFT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'QUEEN BACKWARD RIGHT', 0, -1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING FORWARD', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING FORWARD LEFT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING FORWARD RIGHT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING LEFT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING RIGHT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING BACKWARD', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING BACKWARD LEFT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING BACKWARD RIGHT', 0, 1),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT MOVEMENT_TYPE_ID FROM MOVEMENT_TYPE WHERE NAME = 'SLIDE'), 'KING CASTLE', 0, 1);

INSERT INTO RESTRICTION_TYPE (NAME) VALUES
  ('MOVE COUNT'),
  ('PIECE SLID THROUGH PREVIOUS TURN');

INSERT INTO RESTRICTION_VALUE_TYPE (NAME) VALUES
  ('MOVE COUNT LESS THAN'),
  ('PIECE ID');

INSERT INTO RESTRICTION (AUTHOR_ID, RESTRICTION_TYPE_ID, NAME, RESTRICTION_VALUE_TYPE_ID, VALUE) VALUES
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT RESTRICTION_TYPE_ID FROM RESTRICTION_TYPE WHERE NAME = 'MOVE COUNT'), 'FIRST MOVE', (SELECT RESTRICTION_VALUE_TYPE_ID FROM RESTRICTION_VALUE_TYPE WHERE NAME = 'MOVE COUNT LESS THAN'), 2),
  ((SELECT AUTHOR_ID FROM AUTHOR WHERE FIRST_NAME = 'JOSHUA' AND LAST_NAME = 'BOYD'), (SELECT RESTRICTION_TYPE_ID FROM RESTRICTION_TYPE WHERE NAME = 'PIECE SLID THROUGH PREVIOUS TURN'), 'PAWN SLID THROUGH PREVIOUS TURN', (SELECT RESTRICTION_VALUE_TYPE_ID FROM RESTRICTION_VALUE_TYPE WHERE NAME = 'PIECE ID'), (SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'));

INSERT INTO MOVEMENT_RESTRICTION (MOVEMENT_ID, RESTRICTION_ID) VALUES
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN INITIAL JUMP'), (SELECT RESTRICTION_ID FROM RESTRICTION WHERE NAME = 'FIRST MOVE')),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING CASTLE'), (SELECT RESTRICTION_ID FROM RESTRICTION WHERE NAME = 'FIRST MOVE'));

INSERT INTO CAPTURE_RESTRICTION (MOVEMENT_ID, RESTRICTION_ID) VALUES
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE ENPASSANT LEFT'), (SELECT RESTRICTION_ID FROM RESTRICTION WHERE NAME = 'PAWN SLID THROUGH PREVIOUS TURN')),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE ENPASSANT RIGHT'), (SELECT RESTRICTION_ID FROM RESTRICTION WHERE NAME = 'PAWN SLID THROUGH PREVIOUS TURN'));

INSERT INTO MOVEMENT_COMPONENT (MOVEMENT_DIRECTION_ID, STEP_SIZE) VALUES
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD'), 1),
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD'), 2),
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD'), 1),
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD'), 2),
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT'), 1),
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT'), 2),
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT'), 1),
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT'), 2),
  ((SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'CASTLE'), 2);

INSERT INTO MOVEMENT_MOVEMENT_COMPONENT (MOVEMENT_ID, MOVEMENT_COMPONENT_ID) VALUES
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN SINGLE STEP'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN INITIAL JUMP'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE ENPASSANT LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE ENPASSANT LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE ENPASSANT RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE ENPASSANT RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK FORWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK BACKWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT FORWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT FORWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT FORWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT FORWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT LEFT FORWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT LEFT FORWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT LEFT BACKWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT LEFT BACKWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT RIGHT FORWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT RIGHT FORWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT RIGHT BACKWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT RIGHT BACKWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT BACKWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT BACKWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT BACKWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 2)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT BACKWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP FORWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP FORWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP FORWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP FORWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP BACKWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP BACKWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP BACKWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP BACKWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'FORWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD LEFT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'LEFT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'BACKWARD') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD RIGHT'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'RIGHT') AND STEP_SIZE = 1)),
  ((SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING CASTLE'),(SELECT MOVEMENT_COMPONENT_ID FROM MOVEMENT_COMPONENT WHERE MOVEMENT_DIRECTION_ID = (SELECT MOVEMENT_DIRECTION_ID FROM MOVEMENT_DIRECTION WHERE NAME = 'CASTLE') AND STEP_SIZE = 2));

INSERT INTO PIECE_MOVEMENT (PIECE_ID, MOVEMENT_ID) VALUES
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN SINGLE STEP')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN INITIAL JUMP')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT FORWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT FORWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT LEFT FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT LEFT BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT RIGHT FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT RIGHT BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT BACKWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT BACKWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP FORWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP FORWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP BACKWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP BACKWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING CASTLE'));

INSERT INTO PIECE_CAPTURE (PIECE_ID, MOVEMENT_ID) VALUES
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'PAWN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'PAWN CAPTURE RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'ROOK'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'ROOK BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT FORWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT FORWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT LEFT FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT LEFT BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT RIGHT FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT RIGHT BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT BACKWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KNIGHT'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KNIGHT BACKWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP FORWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP FORWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP BACKWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'BISHOP'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'BISHOP BACKWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN FORWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'QUEEN'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'QUEEN BACKWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING FORWARD RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING RIGHT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD LEFT')),
  ((SELECT PIECE_ID FROM PIECE WHERE NAME = 'KING'), (SELECT MOVEMENT_ID FROM MOVEMENT WHERE NAME = 'KING BACKWARD RIGHT'));

INSERT INTO CASTLE_RULE (NAME) VALUES
  ('JUMP'),
  ('BEGIN SAFE'),
  ('MIDDLE SAFE'),
  ('END SAFE');

INSERT INTO GAME_CASTLE_RULE (GAME_ID, CASTLE_RULE_ID) VALUES
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), (SELECT CASTLE_RULE_ID FROM CASTLE_RULE WHERE NAME = 'JUMP')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), (SELECT CASTLE_RULE_ID FROM CASTLE_RULE WHERE NAME = 'MIDDLE SAFE')),
  ((SELECT GAME_ID FROM GAME WHERE NAME = 'CLASSIC CHESS'), (SELECT CASTLE_RULE_ID FROM CASTLE_RULE WHERE NAME = 'END SAFE'));
